version: '3'
services:
    db:
        image: "postgres"
        container_name: "conduit-api-db"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "55432:5432"
        volumes:
            - postgres:/data/postgres
    api:
        image: 'conduit-api'
        container_name: conduit-api-container
        restart: always
        ports:
            - "9191:80"
        environment:
            PORT: 9191
        depends_on:
            - db

volumes:
    postgres: